services:
  infercode:
    build:
      context: ./src/infercode
      dockerfile: Dockerfile

  type4py:
    build:
      context: ./src/type4py
      dockerfile: Dockerfile

  recoder:
    build:
      context: ./src/recoder
      dockerfile: Dockerfile
