services:
  infercode:
    build:
      context: ./src/infercode
      dockerfile: Dockerfile
    volumes:
      - ./src/infercode/src:/app/infercode
  
  recoder:
    build:
      context: ./src/recoder
      dockerfile: Dockerfile
    volumes:
      - ./src/recoder/src:/app
  
  type4py:
    build:
      context: ./src/type4py
      dockerfile: Dockerfile
    volumes:
      - ./src/type4py/src:/type4py/src

  dear:
    build:
      context: ./src/dear
      dockerfile: Dockerfile
    volumes:
      - ./src/dear/src:/app