services:
  infercode:
    build:
      context: ./src/infercode
      dockerfile: Dockerfile
    volumes:
      - ./src/infercode/src:/app/infercode

  type4py:
    build:
      context: ./src/type4py
      dockerfile: Dockerfile

  recoder:
    build:
      context: ./src/recoder
      dockerfile: Dockerfile

  dear:
    build:
      context: ./src/dear
      dockerfile: Dockerfile
